#version: '3.8'

services:
############################################# Stocks Deployment #############################################################
  stocks:
    image: stock:v1
    ports:
      - "8000:8000"
    networks:
      - stocks_net
    env_file:
      - stock.env

networks:
  stocks_net:
    driver: bridge
